name: Build/release

on:
  push:
    branches:
      - main
    tags-ignore:
      - '**'
  pull_request:
    branches:
      - main

jobs:
  release:
    runs-on: ${{ matrix.os }}

    # Platforms to build on/for
    strategy:
      matrix:
        os: [macos-latest, windows-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v3

      - name: Install Node.js, NPM and Yarn
        uses: actions/setup-node@v3
        with:
          node-version: 16.14.2
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

#      - name: Install Snapcraft
#        uses: samuelmeuli/action-snapcraft@v1
#        # Only install Snapcraft on Ubuntu
#        if: startsWith(matrix.os, 'ubuntu')
#        with:
#          # Log in to Snap Store
#          snapcraft_token: ${{ secrets.snapcraft_token }}

#      - name: Prepare for app notarization (macOS)
#        if: startsWith(matrix.os, 'macos')
#        # Import Apple API key for app notarization on macOS
#        run: |
#          mkdir -p ~/private_keys/
#          echo '${{ secrets.api_key }}' > ~/private_keys/AuthKey_${{ secrets.api_key_id }}.p8

      - name: Build/release Electron app
        uses: KillingJacky/action-electron-builder@v1
        with:
          skip_build: true
          use_vue_cli: true
          npmArgs: "--openssl_fips=''"

          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          github_token: ${{ secrets.github_token }}

          # macOS code signing certificate
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

          # macOS code signing certificate
          windows_certs: ${{ secrets.mac_certs }}
          windows_certs_password: ${{ secrets.mac_certs_password }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
        env:
          # macOS notarization API key
          APPLEID: ${{ secrets.apple_id }}
          APPLEIDPASS: ${{ secrets.apple_id_pass }}
          APPLEASCPROVIDER: ${{ secrets.apple_asc_provider }}
